\section{Process\+Failed\+Exception\+Test Class Reference}
\label{class_symfony_1_1_component_1_1_process_1_1_tests_1_1_process_failed_exception_test}\index{Process\+Failed\+Exception\+Test@{Process\+Failed\+Exception\+Test}}
Inheritance diagram for Process\+Failed\+Exception\+Test\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.303835cm]{class_symfony_1_1_component_1_1_process_1_1_tests_1_1_process_failed_exception_test}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
{\bf test\+Process\+Failed\+Exception\+Throws\+Exception} ()
\item 
{\bf test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output} ()
\item 
{\bf test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output} ()
\end{DoxyCompactItemize}
\subsection*{Additional Inherited Members}


\subsection{Detailed Description}
\begin{DoxyAuthor}{Author}
Sebastian Marek {\tt proofek@gmail.\+com} 
\end{DoxyAuthor}


Definition at line 19 of file Process\+Failed\+Exception\+Test.\+php.



\subsection{Member Function Documentation}
\index{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test@{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test}!test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output@{test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output}}
\index{test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output@{test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output}!Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test@{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test}}
\subsubsection[{test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output}]{\setlength{\rightskip}{0pt plus 5cm}test\+Disabled\+Output\+In\+Failed\+Exception\+Does\+Not\+Populate\+Output (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_process_1_1_tests_1_1_process_failed_exception_test_a6bcfeb6e3957f305ef66963c436b313a}
\doxyref{Tests}{p.}{namespace_symfony_1_1_component_1_1_process_1_1_tests} that Process\+Failed\+Exception does not extract information from process output if it was previously disabled 

Definition at line 96 of file Process\+Failed\+Exception\+Test.\+php.

\index{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test@{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test}!test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output@{test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output}}
\index{test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output@{test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output}!Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test@{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test}}
\subsubsection[{test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output}]{\setlength{\rightskip}{0pt plus 5cm}test\+Process\+Failed\+Exception\+Populates\+Information\+From\+Process\+Output (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_process_1_1_tests_1_1_process_failed_exception_test_ae6658f138298fdbd1e94f5a7b3a31c50}
tests Process\+Failed\+Exception uses information from process output to generate exception message. 

Definition at line 47 of file Process\+Failed\+Exception\+Test.\+php.

\index{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test@{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test}!test\+Process\+Failed\+Exception\+Throws\+Exception@{test\+Process\+Failed\+Exception\+Throws\+Exception}}
\index{test\+Process\+Failed\+Exception\+Throws\+Exception@{test\+Process\+Failed\+Exception\+Throws\+Exception}!Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test@{Symfony\+::\+Component\+::\+Process\+::\+Tests\+::\+Process\+Failed\+Exception\+Test}}
\subsubsection[{test\+Process\+Failed\+Exception\+Throws\+Exception}]{\setlength{\rightskip}{0pt plus 5cm}test\+Process\+Failed\+Exception\+Throws\+Exception (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_process_1_1_tests_1_1_process_failed_exception_test_a2d989e63fffd08170509e9e29702fc24}
tests Process\+Failed\+Exception throws exception if the process was successful. 

Definition at line 24 of file Process\+Failed\+Exception\+Test.\+php.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
vendor/symfony/process/\+Symfony/\+Component/\+Process/\+Tests/{\bf Process\+Failed\+Exception\+Test.\+php}\end{DoxyCompactItemize}
